# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.models.list_instance_snapshots_reply import ListInstanceSnapshotsReply

class TestListInstanceSnapshotsReply(unittest.TestCase):
    """ListInstanceSnapshotsReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListInstanceSnapshotsReply:
        """Test ListInstanceSnapshotsReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListInstanceSnapshotsReply`
        """
        model = ListInstanceSnapshotsReply()
        if include_optional:
            return ListInstanceSnapshotsReply(
                instance_snapshots = [
                    koyeb.api.models.instance_snapshot.InstanceSnapshot(
                        id = '', 
                        name = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        available_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        organization_id = '', 
                        project_id = '', 
                        service_id = '', 
                        deployment_id = '', 
                        regional_deployment_id = '', 
                        instance_id = '', 
                        status = 'INSTANCE_SNAPSHOT_STATUS_INVALID', 
                        type = 'INSTANCE_SNAPSHOT_TYPE_INVALID', 
                        version = '', 
                        messages = [
                            ''
                            ], )
                    ],
                limit = 56,
                offset = 56,
                count = 56,
                has_next = True
            )
        else:
            return ListInstanceSnapshotsReply(
        )
        """

    def testListInstanceSnapshotsReply(self):
        """Test ListInstanceSnapshotsReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
