# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api.api.instance_snapshots_api import InstanceSnapshotsApi


class TestInstanceSnapshotsApi(unittest.TestCase):
    """InstanceSnapshotsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InstanceSnapshotsApi()

    def tearDown(self) -> None:
        pass

    def test_create_instance_snapshot(self) -> None:
        """Test case for create_instance_snapshot

        """
        pass

    def test_delete_instance_snapshot(self) -> None:
        """Test case for delete_instance_snapshot

        """
        pass

    def test_get_instance_snapshot(self) -> None:
        """Test case for get_instance_snapshot

        """
        pass

    def test_list_instance_snapshot_events(self) -> None:
        """Test case for list_instance_snapshot_events

        """
        pass

    def test_list_instance_snapshots(self) -> None:
        """Test case for list_instance_snapshots

        """
        pass


if __name__ == '__main__':
    unittest.main()
