# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from koyeb.api_async.models.instance_snapshot_status import InstanceSnapshotStatus
from koyeb.api_async.models.instance_snapshot_type import InstanceSnapshotType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InstanceSnapshot(BaseModel):
    """
    InstanceSnapshot
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    available_at: Optional[datetime] = None
    deleted_at: Optional[datetime] = None
    organization_id: Optional[StrictStr] = None
    project_id: Optional[StrictStr] = None
    service_id: Optional[StrictStr] = None
    deployment_id: Optional[StrictStr] = None
    regional_deployment_id: Optional[StrictStr] = None
    instance_id: Optional[StrictStr] = None
    status: Optional[InstanceSnapshotStatus] = InstanceSnapshotStatus.INSTANCE_SNAPSHOT_STATUS_INVALID
    type: Optional[InstanceSnapshotType] = InstanceSnapshotType.INSTANCE_SNAPSHOT_TYPE_INVALID
    version: Optional[StrictStr] = None
    messages: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["id", "name", "created_at", "updated_at", "available_at", "deleted_at", "organization_id", "project_id", "service_id", "deployment_id", "regional_deployment_id", "instance_id", "status", "type", "version", "messages"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "available_at": obj.get("available_at"),
            "deleted_at": obj.get("deleted_at"),
            "organization_id": obj.get("organization_id"),
            "project_id": obj.get("project_id"),
            "service_id": obj.get("service_id"),
            "deployment_id": obj.get("deployment_id"),
            "regional_deployment_id": obj.get("regional_deployment_id"),
            "instance_id": obj.get("instance_id"),
            "status": obj.get("status") if obj.get("status") is not None else InstanceSnapshotStatus.INSTANCE_SNAPSHOT_STATUS_INVALID,
            "type": obj.get("type") if obj.get("type") is not None else InstanceSnapshotType.INSTANCE_SNAPSHOT_TYPE_INVALID,
            "version": obj.get("version"),
            "messages": obj.get("messages")
        })
        return _obj


