# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from koyeb.api.models.instance_snapshot import InstanceSnapshot
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ListInstanceSnapshotsReply(BaseModel):
    """
    ListInstanceSnapshotsReply
    """ # noqa: E501
    instance_snapshots: Optional[List[InstanceSnapshot]] = None
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    count: Optional[StrictInt] = None
    has_next: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["instance_snapshots", "limit", "offset", "count", "has_next"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListInstanceSnapshotsReply from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in instance_snapshots (list)
        _items = []
        if self.instance_snapshots:
            for _item_instance_snapshots in self.instance_snapshots:
                if _item_instance_snapshots:
                    _items.append(_item_instance_snapshots.to_dict())
            _dict['instance_snapshots'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListInstanceSnapshotsReply from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instance_snapshots": [InstanceSnapshot.from_dict(_item) for _item in obj["instance_snapshots"]] if obj.get("instance_snapshots") is not None else None,
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "count": obj.get("count"),
            "has_next": obj.get("has_next")
        })
        return _obj


