# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.models.create_instance_snapshot_request import CreateInstanceSnapshotRequest

class TestCreateInstanceSnapshotRequest(unittest.TestCase):
    """CreateInstanceSnapshotRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstanceSnapshotRequest:
        """Test CreateInstanceSnapshotRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstanceSnapshotRequest`
        """
        model = CreateInstanceSnapshotRequest()
        if include_optional:
            return CreateInstanceSnapshotRequest(
                instance_id = '',
                name = '',
                type = 'INSTANCE_SNAPSHOT_TYPE_INVALID'
            )
        else:
            return CreateInstanceSnapshotRequest(
        )
        """

    def testCreateInstanceSnapshotRequest(self):
        """Test CreateInstanceSnapshotRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
