# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.models.egress_policy_mode import EgressPolicyMode

class TestEgressPolicyMode(unittest.TestCase):
    """EgressPolicyMode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEgressPolicyMode(self):
        """Test EgressPolicyMode"""
        # inst = EgressPolicyMode()

if __name__ == '__main__':
    unittest.main()
