# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.models.create_instance_snapshot_reply import CreateInstanceSnapshotReply

class TestCreateInstanceSnapshotReply(unittest.TestCase):
    """CreateInstanceSnapshotReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInstanceSnapshotReply:
        """Test CreateInstanceSnapshotReply
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInstanceSnapshotReply`
        """
        model = CreateInstanceSnapshotReply()
        if include_optional:
            return CreateInstanceSnapshotReply(
                instance_snapshot = koyeb.api_async.models.instance_snapshot.InstanceSnapshot(
                    id = '', 
                    name = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    available_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    organization_id = '', 
                    project_id = '', 
                    service_id = '', 
                    deployment_id = '', 
                    regional_deployment_id = '', 
                    instance_id = '', 
                    status = 'INSTANCE_SNAPSHOT_STATUS_INVALID', 
                    type = 'INSTANCE_SNAPSHOT_TYPE_INVALID', 
                    version = '', 
                    messages = [
                        ''
                        ], )
            )
        else:
            return CreateInstanceSnapshotReply(
        )
        """

    def testCreateInstanceSnapshotReply(self):
        """Test CreateInstanceSnapshotReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
