# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from koyeb.api_async.models.instance_snapshot_status import InstanceSnapshotStatus

class TestInstanceSnapshotStatus(unittest.TestCase):
    """InstanceSnapshotStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInstanceSnapshotStatus(self):
        """Test InstanceSnapshotStatus"""
        # inst = InstanceSnapshotStatus()

if __name__ == '__main__':
    unittest.main()
